export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";

export const NEXT_MONTH = "NEXT_MONTH";
export const PREVIOUS_MONTH = "PREVIOUS_MONTH";

export const POST_DATA_START = "POST_DATA_START";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAIL = "POST_DATA_FAIL";

export const GET_BUDGET_DATA_START = "GET_BUDGET_DATA_START";
export const GET_BUDGET_DATA_SUCCESS = "GET_BUDGET_DATA_SUCCESS";
export const GET_BUDGET_DATA_FAIL = "GET_BUDGET_DATA_FAIL";

export const CHANGE_TYPE = "CHANGE_TYPE";
